---
version: 2
updates:
  # Maintain dependencies for npm modules.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "anipalur"
    assignees:
      - "anipalur"

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "anipalur"
    assignees:
      - "anipalur"
