/* eslint-disable no-unused-vars */
const KEYWORD_MAP = [
  // Constitutional
  {
    id: 'fever',
    keyword: 'fever',
    aliases: [
      'fever',
      'febrile',
      'pyrexia',
    ],
    suggestions: [
      {
        id: 'fever_temperature',
        text: 'Body Temperature',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'fever_chills_rigour',
        text: 'Any Chills or Rigours?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
    ],
  },
  {
    id: 'loa',
    keyword: 'loss of appetite',
    aliases: [
      'loss of appetite',
      'loa',
      'reduced appetite',
      'decreased appetite',
      'lack of appetite',
      'anorexia',
    ],
    suggestions: [
      {
        id: 'loa_cause',
        text: 'Cause of Loss of Appetite',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'loa_low',
        text: 'Any Loss of Weight?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'loa_satiety',
        text: 'Any Early Satiety?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'loa_dieting',
        text: 'Any Dieting?',
        type: 'text',
        sections: ['Social History'],
      },
    ],
  },
  {
    id: 'low',
    keyword: 'loss of weight',
    aliases: [
      'loss of weight',
      'low',
      'reduced weight',
      'decreased weight',
    ],
    suggestions: [
      {
        id: 'low_amount',
        text: 'Amount of Weight Lost',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'With duration',
      },
      {
        id: 'low_cause',
        text: 'Cause of Loss of Weight',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'low_satiety',
        text: 'Any Early Satiety?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'loa_dieting',
        text: 'Any Dieting?',
        type: 'text',
        sections: ['Social History'],
      },
    ],
  },

  // Cardiovascular System
  {
    id: 'chest_pain',
    keyword: 'chest pain',
    aliases: [
      'chest pain',
      'chest tightness',
      'chest discomfort',
      'precordial pain',
    ],
    suggestions: [
      {
        id: 'cp_site',
        text: 'Site of Chest Pain',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'cp_character',
        text: 'Character of Chest Pain',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Crushing, stabbing, burning, tearing, etc.',
      },
      {
        id: 'cp_radiation',
        text: 'Radiation of Chest Pain',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'To neck, arm, jaw, back, etc.',
      },
      {
        id: 'cp_fh',
        text: 'Family History of Heart Disease',
        type: 'text',
        sections: ['Family History'],
      },
    ],
  },

  // Respiratory System
  {
    id: 'cough',
    keyword: 'cough',
    aliases: [
      'cough',
      'sputum',
      'phlegm',
      'mucous',
      'mucus',
      'haemoptysis',
    ],
    suggestions: [
      {
        id: 'cough_frequency',
        text: 'Frequency of Cough',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'cough_productive',
        text: 'Any Sputum?',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Colour, amount, any blood, frequency, etc.',
      },
      {
        id: 'cough_blood',
        text: 'Any Haemoptysis?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'cough_travel',
        text: 'Recent Travel History',
        type: 'textarea',
        sections: ['Social History'],
      },
    ],
  },
  {
    id: 'sob',
    keyword: 'dyspnoea',
    aliases: [
      'shortness of breath',
      'short of breath',
      'sob',
      'dyspnoea',
      'dyspnea',
      'breathlessness',
      'breathless',
      'wheeze',
      'wheezing',
    ],
    suggestions: [
      {
        id: 'sob_trigger',
        text: 'Any Triggers?',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Lying down, at night, exertion, dust, pollen, etc.',
      },
      {
        id: 'sob_breathing',
        text: 'Dyspnoea on Breathing In or Out',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'sob_wheeze',
        text: 'Any Wheezing?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'sob_cough',
        text: 'Any Cough?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'sob_exertion',
        text: 'Any Difficulty Walking or Climbing Stairs?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
    ],
  },

  // GI System
  {
    id: 'abdomen_pain',
    keyword: 'abdominal pain',
    aliases: [
      'abdominal pain',
      'abdomen pain',
      'epigastric pain',
      'umbilical pain',
      'suprapubic pain',
      'hypogastric pain',
      'LUQ pain',
      'RUQ pain',
      'LLQ pain',
      'RLQ pain',
      'LIF pain',
      'RIF pain',
    ],
    suggestions: [
      {
        id: 'abdomen_pain_site',
        text: 'Site of Abdominal Pain',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'abdomen_pain_character',
        text: 'Character of Abdominal Pain',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Crushing, stabbing, burning, tearing, etc.',
      },
      {
        id: 'abdomen_pain_radiation',
        text: 'Radiation of Abdominal Pain',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'To chest, back, etc.',
      },
    ],
  },
  {
    id: 'stool',
    keyword: 'abnormal stool',
    aliases: [
      'stool',
      'abnormal stool',
      'faeces',
      'melena',
      'haematochezia',
      'hematochezia',
    ],
    suggestions: [
      {
        id: 'stool_colour',
        text: 'Colour of Stool',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Brown, black/tarry, pale, oily yellow, bright red, clay-coloured, etc.',
      },
      {
        id: 'stool_blood',
        text: 'Any Blood in Stool?',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Any fresh blood, amount, frequency, etc.',
      },
      {
        id: 'stool_consistency',
        text: 'Consistency of Stool',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Hard, soft, frothy, watery, etc.',
      },
      {
        id: 'stool_amount',
        text: 'Amount of Stool',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'stool_condition',
        text: 'Condition of Stool',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Foul-smelling, mucus, pus, etc.',
      },
      {
        id: 'stool_travel',
        text: 'Recent Food Exposure',
        type: 'text',
        sections: ['Social History'],
      },
    ],
  },
  {
    id: 'bowel_habits',
    keyword: 'altered bowel habits',
    aliases: [
      'diarrhoea',
      'diarrhea',
      'constipation',
      'altered bowel habit',
      'altered bowel habits',
    ],
    suggestions: [
      {
        id: 'bowel_habits_normal',
        text: 'Normal Frequency of Passing Motion',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'bowel_habits_now',
        text: 'Current Frequency of Passing Motion',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'bowel_habits_recent',
        text: 'Most Recent Passing of Motion',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'bowel_habits_regular',
        text: 'Is Passing Motion Regular or Irregular?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'bowel_habits_straining',
        text: 'Any Straining?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'bowel_habits_dyschezia',
        text: 'Any Dyschezia?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'bowel_habits_flatulence',
        text: 'Any Change in Flatulence?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
    ],
  },
  {
    id: 'dysphagia',
    keyword: 'dysphagia',
    aliases: [
      'dysphagia',
      'difficulty swallowing',
      'trouble swallowing',
      'odynophagia',
      'painful swallowing',
      'pain when swallowing',
    ],
    suggestions: [
      {
        id: 'dysphagia_food',
        text: 'Type of Food Causing Dysphagia',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Solid, semi-solid, liquids, etc.',
      },
      {
        id: 'dysphagia_food',
        text: 'Site of Dysphagia',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'dysphagia_odynophagia',
        text: 'Any Odynophagia',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
    ],
  },
  {
    id: 'jaundice',
    keyword: 'jaundice',
    aliases: [
      'jaundice',
      'yellow skin',
      'icterus',
      'yellow sclera',
    ],
    suggestions: [
      {
        id: 'jaundice_fever',
        text: 'Any Fever?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'jaundice_abdomen',
        text: 'Any Abdominal Pain?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'jaundice_pruritus',
        text: 'Any Pruritus?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'jaundice_urine',
        text: 'Any Tea-Coloured Urine?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'jaundice_stool',
        text: 'Any Pale Stools?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'jaundice_haemolysis',
        text: 'Any Haemolytic Blood Disorders?',
        type: 'text',
        sections: ['Medical History'],
        placeholder: 'SCA, thalassaemia, malaria, G6PD deficiency, etc.',
      },
      {
        id: 'jaundice_hbv',
        text: 'HBV Vaccine Status',
        type: 'text',
        sections: ['Medical History'],
      },
      {
        id: 'jaundice_ivdu',
        text: 'Are they an IVDU?',
        type: 'text',
        sections: ['Social History'],
      },
    ],
  },
  {
    id: 'vomit',
    keyword: 'vomiting',
    aliases: [
      'vomit',
      'vomiting',
      'emesis',
      'nausea',
      'regurgitation',
    ],
    suggestions: [
      {
        id: 'vomit_frequency',
        text: 'Frequency of Vomiting',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'vomit_colour',
        text: 'Colour of Vomitus',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Coffee-ground, pink and frothy, green, bright red, etc.',
      },
      {
        id: 'vomit_blood',
        text: 'Any Blood in Vomitus?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'vomit_content',
        text: 'Contents of Vomitus',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Undigested food, digested food, acid, bile, faeces, clear, etc.',
      },
      {
        id: 'vomit_amount',
        text: 'Amount of Vomitus',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Cup-sized, bowl-sized, etc.',
      },
      {
        id: 'vomit_consistency',
        text: 'Consistency of Vomitus',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Solid, frothy, watery, etc.',
      },
      {
        id: 'vomit_pre',
        text: 'Symptoms Before Vomiting',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Nausea, headache, pain, etc.',
      },
      {
        id: 'vomit_trigger',
        text: 'Any Triggers?',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'After meals, bending over, etc.',
      },
      {
        id: 'vomit_travel',
        text: 'Recent Food Exposure',
        type: 'text',
        sections: ['Social History'],
      },
    ],
  },

  // Nervous System
  {
    id: 'seizure',
    keyword: 'seizure',
    aliases: [
      'seizure',
      'seizures',
      'fit',
      'fits',
      'convulsion',
      'convulsions',
      'epilepsy',
    ],
    suggestions: [
      {
        id: 'seizure_pre',
        text: 'Pre-Ictal Symptoms',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'seizure_during',
        text: 'Symptoms During Seizure',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Lies still, jerking, bites tongue, urination, etc.',
      },
      {
        id: 'seizure_post',
        text: 'Post-Ictal Symptoms',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Drowsiness, confusion, etc.',
      },
    ],
  },

  // MSK System
  {
    id: 'arthralgia',
    keyword: 'arthralgia',
    aliases: [
      'arthralgia',
      'joint pain',
    ],
    suggestions: [
      {
        id: 'arthralgia_swelling',
        text: 'Any Joint Swelling?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'arthralgia_rom',
        text: 'Any Difficulty Moving Joints?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'arthralgia_adl',
        text: 'Activities of Daily Living',
        type: 'textarea',
        sections: ['Social History'],
      },
    ],
  },

  // Urinary System
  {
    id: 'urine',
    keyword: 'abnormal urine',
    aliases: [
      'urine',
      'abnormal urine',
    ],
    suggestions: [
      {
        id: 'urine_colour',
        text: 'Colour of Urine',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Brown, foamy, frothy, sandy, tea-coloured, etc.',
      },
      {
        id: 'urine_blood',
        text: 'Any Blood in Urine?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'urine_volume',
        text: 'Volume of Urine',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'urine_smell',
        text: 'Smell of Urine',
        type: 'text',
        sections: ['History of Presenting Illness'],
        placeholder: 'Foul-smelling, sweet-smelling, etc.',
      },
      {
        id: 'urine_sexual',
        text: 'Sexual History',
        type: 'textarea',
        sections: ['Social History'],
      },
    ],
  },
  {
    id: 'luts',
    keyword: 'LUTS',
    aliases: [
      'luts',
      'frequency',
      'urgency',
      'dysuria',
      'painful urination',
      'pain when urinating',
      'hesitancy',
    ],
    suggestions: [
      {
        id: 'luts_normal',
        text: 'Normal Frequency of Urination',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'luts_frequency',
        text: 'Any Frequency?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'luts_urgency',
        text: 'Any Urgency?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'luts_dysuria',
        text: 'Any Dysuria?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'luts_hesitancy',
        text: 'Any Hesitancy?',
        type: 'text',
        sections: ['History of Presenting Illness'],
      },
      {
        id: 'urine_sexual',
        text: 'Sexual History',
        type: 'textarea',
        sections: ['Social History'],
      },
    ],
  },
];
