---
name: Request an enhancement
description: Have an idea to improve an existing feature? Let me know here!
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |-
        Firstly, thanks for taking the time to request an enhancement!
        Please ensure your enhancement has not been requested before on the [Issues tab](https://github.com/anipalur/listhis/issues "Visit the Issues tab.").
        Duplicate or unrelated issues will be closed.
  - type: textarea
    id: related-problem
    attributes:
      label: Related Problem
      description: Is an existing problem related to your request? If so, please describe it.
      value: I'm always frustrated when...
  - type: textarea
    id: enhancement-description
    attributes:
      label: Enhancement Description
      description: Describe your enhancement. How would it improve an existing feature?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add additional information not covered elsewhere here.
      value: None
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this issue, you agree to abide by our
        [Code of Conduct](https://github.com/anipalur/listhis/blob/main/CODE_OF_CONDUCT.md "View the Code of Conduct.").
      options:
        - label: I agree to abide by the Code of Conduct.
          required: true
