---
# Checks if all .md files have been linted correctly.
name: Lint
run-name: Check Markdown files
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  lint:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run markdownlint
        run: npm run is-linted:md
      - name: Run eslint
        run: npm run is-linted:js
